language: csharp
mono:
- latest
install:
- nuget restore
script:
- ./.ci.sh
env:
  secure: H5UoSKGyL1mhSSmrEK9plIbOmETKGPndPJagovR9YdfcFuXRZe/TBQTUCvgL/vgLHnZfdVq9A5oy2ZHwECQl0374FARzjgwJNJDXsRtpR1hcq21Qs8pGYV/0XG3k1ObDg21LZgTdbL3NHnwYEG9ns0hqUUKpE+curQdHSklGrgJHfjd9+gjPSUVmUJbXetZoVJFklgwPGjJcr/PKOyOLdTNRJdSFjjv+WXRtKIljseo9KlwG4utw/Oga5EwtdOpD6LapqgUu/J0bph+5zmcrwoIrV/IGaava84cJaL44HrXpPyTQBRp8ZW2s4hZ0dd16IOqVI3LOa3g0qpOe5eXQ22IxnQ3olh36vpffz7d7zQ3PfKENyEtb2H9I5LKxSGzWmV8xr+HO3ZZqFoocPdisNzzyLR5aw3PJiY2nq17YDMlHCya9vnR8Q+g+uE29jS8wFfXD0BvPGINyGV8XPqRXWmT91XwQ1KmPxwH5r9/I+U2mtZ/yioT7OEViEPpgj5Bc+XyCtB04vdyXvPq50X5+eq7euwJqty7NE8M0unVuidSqgYYTmId0i6wWqY4mwiJUP2/X4bqxzn1NyQ770zPR5c4DM5YeEWXGqQSaD3ZXs7mYoYOqSWQwyEOZWbG8GPRVWjfK+ST0OKAQPNnPwXOLinhDXyR/aGJcMT5dzQxATqs=
